version: '3'
services:
  web:
    build: .
    env_file:
      .env
    ports:
      - 8000:${PORT}
    volumes:
      # Bind-mount for quick local testing without rebuilding container.
      - ./haproxy.cfg:/app/haproxy.cfg:ro
      - ./docker-entrypoint.py:/app/docker-entrypoint.py:ro
      - ./renew-certificate.py:/app/renew-certificate.py:ro
      - ./services.d:/etc/services.d:ro
